name: core_entity
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #Module
  core:
    path: ../core

  #comparing dart objects
  equatable: ^2.0.5
  #Database
  floor: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 7.0.8
  floor_generator: 1.4.2
  build_runner: 2.4.6
